### ISSUE TITLE
Add Bulk Insert

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/orm#313]
Should be a way to insert multiple records at once. This will simply create a insert statement like this:

```python
User.bulk_insert([
    {"user": "Joe"},
    {"user": "bill"},
    {"user": "John"},
])
```

This will produce a query like this:

```
INSERT INTO `users` (`username`) VALUES("Joe"),("Bill"),("John")
```

**Comment by girardinsamuel** [comment]
@josephmancuso maybe we should use this name:
```
User.bulk_create([])
```
as we are using `User.create()` for one record

**Comment by josephmancuso** [comment]
Yeah I think that's fine.

**Comment by jpmateo022** [comment]
I think  ```User.create([])``` looks good similar to Eloquent. Though I really hope we have this soon. It's actually a very critical feature to have since putting create() inside a loop is a bad practice and will cause performance problems. Masonite ORM doesn't seem to have a way to construct a raw SQL Insert query which can be an alternative solution or workaround.

**Comment by josephmancuso** [comment]
@jpmateo022 Ok I can work on this tonight. Both those features

**Comment by jpmateo022** [comment]
@josephmancuso Thank you so much!
