### ISSUE TITLE
Missing drop_primary function

### ISSUE THREAD

**Issue by rodrigopv** [MasoniteFramework/orm#445]
**Describe the bug**
When trying to creating a migration that needs to remove a primary key, according to docs `table.drop_primary` should do this work.

**To Reproduce**
1. Create migration to update table
2. Add line to remove primary key `table.drop_primary('users_id_primary')`
3. Expect migration to fail with `'Blueprint' object has no attribute 'drop_primary'`

**Expected behavior**
drop_primary should allow to delete primary_keys

![image](https://user-images.githubusercontent.com/198869/114470338-b5221a00-9bbc-11eb-924c-83da690e9a96.png)

**What database are you using?**
 - Type: Postgres
 - Version13
 - Masonite ORM 1.0.46

**Additional context**
Any other steps you are doing or any other related information that will help us debug the problem please put here.

**Comment by rodrigopv** [comment]
Maybe one way to fix this is to backport this implementation from orator, but something makes me think that maybe it was intentional to left this out.

**Comment by josephmancuso** [comment]
This was intentially left out at the time.

The main reason it was removed was because in order to drop a primary constraint, a table level constraint was required to be created.

We previously were creating column level constraints (setting a column as the primary key). This is fine but it does not allow you to set a primary key name and therefore you do not know what the constraint name is to drop. (each database implements its own auto generated constraint name).

We can implement this now as we have since implemnted table level constraints for primary keys like this here: https://github.com/MasoniteFramework/orm/blob/335b64d94611a8eb9f7473ef576460e70c0cd3da/src/masoniteorm/schema/platforms/MSSQLPlatform.py#L189-L192 

**This would be very similiar to dropping a unique constraint or other table level constraint**
