### ISSUE TITLE
It is creating migration in order but you are not able to migrate at all.

### ISSUE THREAD

**Issue by yubarajshrestha** [MasoniteFramework/orm#717]
I think this is solve https://github.com/MasoniteFramework/masonite/blob/4.0/src/masonite/packages/providers/PackageProvider.py#L150

_Originally posted by @josephmancuso in https://github.com/MasoniteFramework/orm/issues/626#issuecomment-1150611459_

**Comment by girardinsamuel** [comment]
Can you post the stack trace ? 🙏

**Comment by josephmancuso** [comment]
The issue is we added the index to the migration name which is fine and fixes the ordering

but the problem is we were splitting the migration name by 4 `_` to get the class name in the ORM. 

Since we added an extra `_` before and after the index that would cause us to get a migration name like `1CreateUsersTable` and we would not be able to locate the class name.

This is fixed in Masonites 717 PR
