### ISSUE TITLE
Issue when serializing a model with pickle

### ISSUE THREAD

**Issue by LordDeveloper** [MasoniteFramework/orm#720]
```python
from databases.models import Account
import pickle 

accounts = Account.is_logged_in().in_random_order()\
    .take(100).get().chunk(10)

pickle.dumps(accounts)
```

Error:
```text
_pickle.PicklingError: Can't pickle <function Account.is_logged_in at 0x7f6b36016a70>: it's not the same object as databases.models.Account.Account.is_logged_in
```

is_logged_in is a model scope

**Comment by josephmancuso** [comment]
For future people who see this issue, Masonite ORM models with scopes cannot be pickled. The solution would be to use a different module like `dill` instead of pickle or if pickle is used inside the library you're trying to use then find a similar module that uses dill under the hood. Like `pathos.multiprocessing` instead of `multiprocessing`
